C96 namelists
VulcanClimateModeling/fv3gfs-fortran pull request #117
Opened 2021-01-07 20:48 UTC by oelbert

Adding namelists for C96 runs

2021-01-08 01:07 UTC, rheacangeo commented
Very cool! Sadly it failed weirdly to generate the serialization data (https://jenkins.ginko.ch/job/fv3gfs-fortran-generate-test-data/186/console), but hopefully we can figure it out.
15:17:53 cat: /rundir/env.out: No such file or directory
15:17:53 >>>>> Aborting
huh?

2021-01-08 21:52 UTC, ofuhrer commented
Some comments from my side:
- Should we not default all I/O (including diagnostics, restarts, etc.) to off since the main focus of these namelists is to collect performance numbers which should not be polluted by I/O. Should it not be an active decision to switch on I/O for validation purposes and longer runs (we will only be doing 60 timesteps or so)?
- If `dycore_only=.true.` and `fv_sg_adj=0` we are all set an we need to run is `fv_dynamics`. Is the idea we start with that and potentially switch on `fv_sg_adj=X` once we have the code ported? Or is sub-grid scale mixing not doing anything within the first couple of timesteps of the baroclinic test case?
- Is the argument for `do_sat_adj=.false.` the fact that humidity is close to zero anyways and it would do nothing?
- What does `fill_dp=.true./.false.` do? Why has it flipped?
- Are you sure about `k_split=7; n_split=8`? Are those the values they use for DYAMOND (c3072)?
  ![image](https://user-images.githubusercontent.com/5963462/104067614-52ce0d80-51b8-11eb-95fd-713571722d9d.png)
- What is the plan for `dt_atmos` for c96, c128, c192, c256? I see you left it constant from c48 to c96. What is the timestep they are using for the DYAMOND (c3072) runs?
- Are the settings for the sponge representative of the DYAMOND runs (c3072)?

2021-01-08 21:57 UTC, ofuhrer requested changes
I made some comments with questions and suggestions.

2021-01-11 19:59 UTC, rheacangeo commented on tests/serialized_test_data_generation/configs/c96_54ranks_baroclinic.yml
> +data_table: default
before this is merged in we should make sure PR 118 is merged to master or here and also generate the c96_54ranks_baroclinic data (to make sure that won't crash jenkins every time that runs). Depending on how long this one takes, we might want to change the frequency of the jenkins validation. But the c96_6ranks was pretty quick.

2021-01-11 20:19 UTC, rheacangeo reviewed
Looks good! Some open questions, mostly the ones Oli brought up and the settings changed compared to the c12 case.

2021-01-11 20:19 UTC, rheacangeo commented on tests/serialized_test_data_generation/configs/c96_6ranks_baroclinic.yml
> +    seconds: 45
How many timesteps do we want these configurations to specify? For the baseline run, these will have to change... but we probably don't want 60 timesteps or whatever here running in jenkins... I wonder how long that takes. Are there any other namelist parameters that would have to change for the performance baseline and comparison runs?

2021-01-11 20:19 UTC, rheacangeo commented on tests/serialized_test_data_generation/configs/c96_6ranks_baroclinic.yml
> +    fill_dp: false
I am confused as to how this is true for the other configurations and doesn't cause validation issues, we didn't port mix_dp -- looks like it only does something when delp < dpmin, so maybe we have just gotten lucky? It seems like a setting that should be false for all configs

2021-01-11 20:19 UTC, rheacangeo commented on tests/serialized_test_data_generation/configs/c96_6ranks_baroclinic.yml
> +    n_sponge: 20
how did you decide on these?

2021-01-12 18:26 UTC, rheacangeo commented
the 54 ranks crashes in jenkins for an unknown reason (https://jenkins.ginko.ch/job/fv3gfs-fortran-generate-test-data/204/console) .. we might want to not include that in this round unless we can determine the problem.

2021-01-12 20:13 UTC, ofuhrer approved these changes

2021-01-13 17:41 UTC, rheacangeo approved these changes
Yay! Looks good. thanks for your patience with all the janky snafus

2021-01-13 17:46 UTC, merged